name: CI-CD

# gatilhos para disparar a automação
on:
  push: 
    branches: ["main"]  # assim que ocorre um push na branch main
  workflow_dispatch:  # disparar manualmente
  
# sequencia de etapas no workflow
jobs:
  ci: # declaracao do job de CI
    runs-on: ubuntu-latest  # ambiente/agente de execucao
    steps:
      - name: Obter o codigo do projeto 
        uses: actions/checkout@v4 # uso de uma action para trazer o codigo do repositorio para o ambiente
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construcao da Imagem Docker
        run: echo "Executando o comando Docker Build"
      - name: Envio da Imagem Docker
        run: echo "Executando o comando Docker Push"
  
  cd: # declaracao do job de CD
    runs-on: ubuntu-latest  # ambiente/agente de execucao
    needs: [ci]  # garante que o job de CD executa apenas depois do job de CI
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando AWS Configure"
      - name: Configurar o kubectl
        run: echo "Executando o comando AWS EKS update-kubeconfig"
      - name: Aplicar os manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"
        
