name: CI-CD

# gatilhos para disparar a automação
on:
  push: 
    branches: ["main"]  # assim que ocorre um push na branch main
  workflow_dispatch:  # disparar manualmente
  
# sequencia de etapas no workflow
jobs:
  ci: # declaracao do job de CI
    runs-on: ubuntu-latest  # ambiente/agente de execucao
    steps:
      - name: Obter o codigo do projeto 
        uses: actions/checkout@v4
        
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construcao e envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            douglasci/fake-shop:latest
            douglasci/fake-shop:v${{ github.run_number }}
  
  cd: # declaracao do job de CD
    runs-on: ubuntu-latest  # ambiente/agente de execucao
    needs: [ci]  # garante que o job de CD executa apenas depois do job de CI
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando AWS Configure"
      - name: Configurar o kubectl
        run: echo "Executando o comando AWS EKS update-kubeconfig"
      - name: Aplicar os manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"
        
